import { CommonModule, CurrencyPipe, PercentPipe } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { CardModule } from 'primeng/card';
import { TableModule } from 'primeng/table';
import { DropdownModule } from 'primeng/dropdown';
import { FormsModule } from '@angular/forms';
import { NgxSpinnerService, NgxSpinnerModule } from 'ngx-spinner';
import { MessageService } from 'primeng/api';
import { ToastModule } from 'primeng/toast';
import { timer } from 'rxjs';
import { LoadingDataBannerComponent } from '../../../../../../shared/components/loading-data-banner/loading-data-banner.component';
import { OrdersService, Order, Address, OrderDetail, SingleOrderResponse } from '../../service/orders.service';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// IMPORTANT: Import the generated font definition file
// This file is generated by a tool (e.g., jspdf-customfonts) and
// contains the font data and registration logic for jsPDF.
// Make sure the path is correct.
import './../../../../../../../assets/font/Amiri-Regular-normal.js'; 

interface StatusOption {
  label: string;
  value: string;
  icon: string;
  color: string;
}

@Component({
  selector: 'app-view-order',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    CurrencyPipe,
    PercentPipe,
    ButtonModule,
    CardModule,
    TableModule,
    DropdownModule,
    ToastModule,
    LoadingDataBannerComponent,
    NgxSpinnerModule,
  ],
  templateUrl: './view-order.component.html',
  styleUrls: ['./view-order.component.scss'],
  providers: [MessageService],
})
export class ViewOrderComponent implements OnInit {
  order!: Order;
  userDetails: Address[] = [];
  userAddress: Address[] = [];
  userPromo: { id: number; value: string }[] = [];
  userOrders: OrderDetail[] = [];
  isDownloading = false;
  // No need for a separate fontLoaded flag if you import it directly
  // fontLoaded = false;

  private activatedRoute = inject(ActivatedRoute);
  private router = inject(Router);
  private ordersService = inject(OrdersService);
  private ngxSpinnerService = inject(NgxSpinnerService);
  private messageService = inject(MessageService);

  ngOnInit(): void {
    this.fetchData();
    // No need to dynamically load the script if imported directly
    // this.loadAmiriFont();
  }

  fetchData(): void {
    const orderId = this.activatedRoute.snapshot.paramMap.get('id');
    if (orderId) {
      this.ordersService.getOrderById(orderId).subscribe({
        next: (response: SingleOrderResponse) => {
          this.order = response.order;
          console.log(this.order);
          this.userDetails = [this.order.address];
          this.userAddress = [this.order.address];
          if (this.order.promo_code_id) {
            this.userPromo = [{ id: this.order.promo_code_id, value: this.order.promo_code_value }];
          }
          this.userOrders = this.order.details;
        },
        error: (err) => {
          console.error('Failed to load order', err);
          this.messageService.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Failed to load order details.',
            life: 3000,
            key: 'orderStatusMessage',
          });
        },
      });
    }
  }

  backToOrders(): void {
    if (this.router.url.includes('history')) {
      this.router.navigate(['/dashboard/orders/history']);
    } else {
      this.router.navigate(['/dashboard/orders']);
    }
  }

  getItemDescription(item: OrderDetail): string {
    let details = [];
    if (item.quantity) {
      details.push(`${item.quantity}x`);
    }
    if (item.product?.en_name) {
      details.push(item.product.en_name);
    }
    return details.join(' ');
  }

  // Remove loadAmiriFont as the font is now imported directly
  // async loadAmiriFont() { /* ... */ }

  downloadOrderReceipt(): void {
    this.isDownloading = true;

    const logoData = './assets/favicon_io/web-app-manifest-192x192.png';
    const sarData = './assets/images/sar.png';
    const logoImg = new Image();
    const sarImg = new Image();
    logoImg.crossOrigin = 'Anonymous';
    sarImg.crossOrigin = 'Anonymous';
    logoImg.src = logoData;
    sarImg.src = sarData;

    // Wait for both images to load
    Promise.all([
      new Promise((resolve) => (logoImg.onload = resolve)),
      new Promise((resolve) => (sarImg.onload = resolve)),
    ]).then(() => {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      const pageHeight = doc.internal.pageSize.height;

      // Set Amiri font. The name 'Amiri-Regular' should match what
      // is defined in your Amiri-Regular-normal.js file.
      // Make sure this font name is consistent.
      doc.setFont('Amiri-Regular', 'normal'); // Use 'normal' or 'bold'
      // You can also set a fallback font if needed, but the primary font
      // should be handled by the .js import.

      // Margins and content width
      const leftMargin = 10;
      const rightMargin = 10;
      const contentWidth = pageWidth - leftMargin - rightMargin;

      // Add logo in top-left
      doc.addImage(logoImg, 'PNG', leftMargin, 5, 30, 30);

      // Title - centered, moved down slightly
      doc.setFontSize(16);
      doc.setFont('Amiri-Regular', 'bold'); // Use the correct font name here too
      doc.text('ORDER RECEIPT', pageWidth / 2, 25, { align: 'center' });

      // Simple divider line
      doc.setLineWidth(0.2);
      doc.line(leftMargin, 35, pageWidth - rightMargin, 35);

      // Order Information - compact layout
      let yPos = 40;
      doc.setFontSize(10);
      doc.setFont('Amiri-Regular', 'normal'); // Use the correct font name here too

      // Compact order details
      const orderDetails = [
        `Order #: ${this.order.id}`,
        `Date: ${this.order.order_date}`,
        `Customer: ${this.order.address.first_name} ${this.order.address.last_name}`,
        `Phone: ${this.order.address.phone}`,
        `Address: ${this.order.address.city} - ${this.order.address.address || ''}`,
      ];

      orderDetails.forEach((detail) => {
        doc.text(detail, leftMargin, yPos);
        yPos += 5;
      });

      // Add spacing before items table
      yPos += 10;

      // Items Table - compact styling
      const tableData = this.userOrders.map((item) => [
        this.getItemDescription(item),
        item.quantity.toString(),
        `${parseFloat(item.unit_price).toFixed(2)}`, // Remove SAR text
      ]);

      // Create compact items table
      autoTable(doc, {
        startY: yPos,
        head: [['Item', 'Qty', 'Price']],
        body: tableData,
        margin: { left: leftMargin, right: rightMargin },
        styles: {
          fontSize: 9,
          cellPadding: 3,
          lineColor: [150, 150, 150],
          lineWidth: 0.2,
          font: 'Amiri-Regular', // Use the correct font name
        },
        headStyles: {
          fillColor: [255, 255, 255],
          textColor: [0, 0, 0],
          fontStyle: 'bold',
          fontSize: 9,
          halign: 'left',
          font: 'Amiri-Regular', // Use the correct font name
        },
        bodyStyles: {
          textColor: [0, 0, 0],
          font: 'Amiri-Regular', // Use the correct font name
        },
        columnStyles: {
          0: { cellWidth: contentWidth * 0.6, halign: 'left' },
          1: { cellWidth: contentWidth * 0.1, halign: 'center' },
          2: { cellWidth: contentWidth * 0.3, halign: 'right' },
        },
        didDrawCell: (data) => {
          // Handle SAR currency images
          if (data.column.index === 2 && data.cell.section === 'body') {
            const priceText = data.cell.text[0];
            const textWidth = doc.getTextWidth(priceText);
            const textPosX = data.cell.x + data.cell.width - textWidth - 2;
            const textPosY = data.cell.y + data.cell.height / 2 + 2;
            doc.addImage(sarImg, 'PNG', textPosX - 9, textPosY - 3.5, 5, 3);
          }
        },
        theme: 'grid',
      });

      // Get position after items table
      const tableEndY = (doc as any).lastAutoTable.finalY + 10;

      // Summary section - compact and clean
      const subtotal = parseFloat(this.order.subtotal);
      const shipping = parseFloat(this.order.shipping);
      const tax = parseFloat(this.order.tax);
      const total = parseFloat(this.order.total);

      // Summary data
      const summaryData = [
        ['Subtotal:', `${subtotal.toFixed(2)}`],
        ['Shipping:', `${shipping.toFixed(2)}`],
        ['Tax:', `${tax.toFixed(2)}`],
        ['Promo Code:', `- ${this.order.promo_code_value || '0.00'}`],
        ['Total:', `${total.toFixed(2)}`],
      ];

      autoTable(doc, {
        startY: tableEndY,
        body: summaryData,
        margin: { left: leftMargin + contentWidth * 0.5, right: rightMargin },
        styles: {
          fontSize: 10,
          cellPadding: 3,
          lineColor: [150, 150, 150],
          lineWidth: 0.2,
          font: 'Amiri-Regular', // Use the correct font name
        },
        columnStyles: {
          0: { cellWidth: contentWidth * 0.25, halign: 'left', fontStyle: 'bold' },
          1: { cellWidth: contentWidth * 0.25, halign: 'right' },
        },
        didDrawCell: (data) => {
          // Handle SAR currency images in summary
          if (data.column.index === 1 && data.cell.section === 'body') {
            const priceText = data.cell.text[0];
            const textWidth = doc.getTextWidth(priceText);
            const textPosX = data.cell.x + data.cell.width - textWidth - 2;
            const textPosY = data.cell.y + data.cell.height / 2 + 2;
            doc.addImage(sarImg, 'PNG', textPosX - 9, textPosY - 3.5, 5, 3);
          }

          // Style the total row
          if (data.row.index === 4) {
            // Total row
            data.cell.styles.fontStyle = 'bold';
            data.cell.styles.fontSize = 11;
          }
        },
        theme: 'plain',
      });

      // Footer section
      const footerY = Math.max((doc as any).lastAutoTable.finalY + 25, pageHeight - 30);

      // Add a line above footer
      doc.setLineWidth(0.3);
      doc.line(leftMargin, footerY - 10, pageWidth - rightMargin, footerY - 10);

      // Footer text
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.setFont('Amiri-Regular', 'normal'); // Use the correct font name

      const generatedText = `Generated on: ${new Date().toLocaleString()}`;
      const receiptText = `Order Receipt - ${this.order.id}`;

      doc.text(generatedText, leftMargin, footerY);
      doc.text(receiptText, pageWidth - rightMargin, footerY, { align: 'right' });

      // Save the PDF
      doc.save(`Order_Receipt_${this.order.id}.pdf`);

      // Reset downloading state and show success message
      this.isDownloading = false;
      this.messageService.add({
        severity: 'success',
        summary: 'Download Complete',
        detail: 'Receipt has been downloaded successfully as PDF.',
        life: 3000,
        key: 'orderStatusMessage',
      });
    });
  }

  statusSteps = ['pending', 'confirmed', 'on the way', 'delivered'];

  getStatusClass(status: string): string {
    switch (status) {
      case 'pending':
        return 'bg-yellow-200 text-yellow-800';
      case 'confirmed':
        return 'bg-blue-200 text-blue-800';
      case 'on the way':
        return 'bg-orange-200 text-orange-800';
      case 'delivered':
        return 'bg-green-200 text-green-800';
      default:
        return '';
    }
  }

  getAvailableStatusOptions(currentStatus: string): StatusOption[] {
    const statusWithStyles: StatusOption[] = [
      { label: 'Pending', value: 'pending', icon: 'pi pi-inbox', color: 'text-yellow-600' },
      { label: 'Confirmed', value: 'confirmed', icon: 'pi pi-check-circle', color: 'text-blue-600' },
      { label: 'on the way', value: 'on the way', icon: 'pi pi-truck', color: 'text-orange-600' },
      { label: 'Delivered', value: 'delivered', icon: 'pi pi-box', color: 'text-green-600' },
    ];

    const currentIndex = this.statusSteps.indexOf(currentStatus);

    return statusWithStyles.map((status, index) => ({
      ...status,
      disabled: status.value === 'pending' || index < currentIndex,
    }));
  }

  updateOrderStatus(order: Order): void {
    this.ngxSpinnerService.show('actionsLoader');
    this.messageService.clear('orderStatusMessage');

    this.ordersService.updateOrderStatus(order.id.toString(), { order_status: order.order_status }).subscribe({
      next: (response) => {
        timer(200).subscribe(() => this.ngxSpinnerService.hide('actionsLoader'));
        this.order = response.order;
        this.messageService.add({
          severity: 'success',
          summary: 'Status Updated',
          detail: `Order status changed to "${order.order_status}"`,
          life: 3000,
          key: 'orderStatusMessage',
        });
      },
      error: (err) => {
        timer(200).subscribe(() => this.ngxSpinnerService.hide('actionsLoader'));
        console.error('Error updating status', err);
        console.error('Error updating status', err);
        this.messageService.add({
          severity: 'error',
          summary: 'Update Failed',
          detail: 'Could not update order status.',
          life: 3000,
          key: 'orderStatusMessage',
        });
      },
    });
  }
}